"""One-shot merge of two source lucent.db files into the new container volume.

Strategy:
  1. Copy hive's lucent.db to the target as the base (preserves its IDs and
     all 493 memories / 204 nodes / 185 edges).
  2. For each entry in skippy's lucent.db, INSERT into the target with a
     fresh autogenerated id. Maintain a per-table old_id → new_id map.
  3. Edges are remapped using the node-id map.

Run from /home/daniel/Storage/Dev/hive_nervous_system/.
"""
from __future__ import annotations

import shutil
import sqlite3
import sys
from collections import Counter
from pathlib import Path

HIVE_DB = Path("/home/daniel/Storage/Dev/hive_mind/data/lucent.db")
SKIPPY_DB = Path("/home/daniel/Storage/hive_mind_skippy/data/lucent.db")
TARGET_DB = Path("/home/daniel/Storage/Dev/hive_nervous_system/data/lucent.db")


def main() -> int:
    if not HIVE_DB.is_file():
        sys.exit(f"hive db not found: {HIVE_DB}")
    if not SKIPPY_DB.is_file():
        sys.exit(f"skippy db not found: {SKIPPY_DB}")
    if TARGET_DB.exists():
        TARGET_DB.unlink()

    # Step 1: copy hive's DB as the base.
    shutil.copy2(str(HIVE_DB), str(TARGET_DB))
    print(f"copied {HIVE_DB} -> {TARGET_DB}")

    target = sqlite3.connect(str(TARGET_DB))
    target.row_factory = sqlite3.Row
    skippy = sqlite3.connect(str(SKIPPY_DB))
    skippy.row_factory = sqlite3.Row

    pre = {
        "memories": target.execute("SELECT COUNT(*) FROM memories").fetchone()[0],
        "nodes": target.execute("SELECT COUNT(*) FROM nodes").fetchone()[0],
        "edges": target.execute("SELECT COUNT(*) FROM edges").fetchone()[0],
    }
    print(f"target after copy: {pre}")

    # Step 2: merge skippy's nodes, mapping old_id → new_id.
    node_id_map: dict[int, int] = {}
    node_cols = [
        "agent_id", "type", "name", "first_name", "last_name",
        "properties", "data_class", "tier", "source",
        "as_of", "created_at", "updated_at",
    ]
    placeholders = ", ".join(["?"] * len(node_cols))
    for r in skippy.execute(f"SELECT id, {', '.join(node_cols)} FROM nodes"):
        cur = target.execute(
            f"INSERT INTO nodes ({', '.join(node_cols)}) VALUES ({placeholders})",
            tuple(r[c] for c in node_cols),
        )
        node_id_map[r["id"]] = cur.lastrowid
    target.commit()
    print(f"merged {len(node_id_map)} nodes (skippy) into target")

    # Step 3: merge skippy's edges, remapping source_id and target_id.
    edge_cols = [
        "agent_id", "source_id", "target_id", "type",
        "as_of", "source", "data_class", "tier", "created_at",
    ]
    edge_placeholders = ", ".join(["?"] * len(edge_cols))
    edges_inserted = 0
    edges_skipped = 0
    for r in skippy.execute(f"SELECT id, {', '.join(edge_cols)} FROM edges"):
        new_source = node_id_map.get(r["source_id"])
        new_target = node_id_map.get(r["target_id"])
        if new_source is None or new_target is None:
            edges_skipped += 1
            continue
        vals = []
        for c in edge_cols:
            if c == "source_id":
                vals.append(new_source)
            elif c == "target_id":
                vals.append(new_target)
            else:
                vals.append(r[c])
        target.execute(
            f"INSERT INTO edges ({', '.join(edge_cols)}) VALUES ({edge_placeholders})",
            tuple(vals),
        )
        edges_inserted += 1
    target.commit()
    print(f"merged {edges_inserted} edges (skippy) into target ({edges_skipped} skipped)")

    # Step 4: merge skippy's memories.
    mem_cols = [
        "agent_id", "content", "embedding", "tags", "source",
        "data_class", "tier", "as_of", "expires_at", "superseded",
        "recurring", "codebase_ref", "created_at",
    ]
    mem_placeholders = ", ".join(["?"] * len(mem_cols))
    mem_inserted = 0
    for r in skippy.execute(f"SELECT {', '.join(mem_cols)} FROM memories"):
        target.execute(
            f"INSERT INTO memories ({', '.join(mem_cols)}) VALUES ({mem_placeholders})",
            tuple(r[c] for c in mem_cols),
        )
        mem_inserted += 1
    target.commit()
    print(f"merged {mem_inserted} memories (skippy) into target")

    # Step 5: verify post-counts and per-agent breakdown.
    post = {
        "memories": target.execute("SELECT COUNT(*) FROM memories").fetchone()[0],
        "nodes": target.execute("SELECT COUNT(*) FROM nodes").fetchone()[0],
        "edges": target.execute("SELECT COUNT(*) FROM edges").fetchone()[0],
    }
    print(f"target after merge: {post}")

    print("\nper-agent memory counts:")
    by_agent: Counter[str] = Counter()
    for r in target.execute("SELECT agent_id FROM memories"):
        by_agent[r["agent_id"]] += 1
    for agent, count in sorted(by_agent.items(), key=lambda x: -x[1]):
        print(f"  {agent[:40]:40}  {count}")

    print("\nidentity nodes (type='Mind'):")
    for r in target.execute(
        "SELECT name, agent_id, data_class FROM nodes WHERE type = 'Mind'"
    ):
        print(f"  {dict(r)}")

    target.close()
    skippy.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
